name = "bookmark-navigation"
compatibility_date = "2023-10-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
d1_databases = [
  { binding = "DB", database_name = "bookmark-db", database_id = "YOUR_DATABASE_ID" }
]

[[kv_namespaces]]
binding = "KV"
id = "5eb7a3ae36574f7199e92f46e5537098"
preview_id = "5eb7a3ae36574f7199e92f46e5537098"

[env.development]
d1_databases = [
  { binding = "DB", database_name = "bookmark-db", database_id = "YOUR_DEV_DATABASE_ID" }
]

[[kv_namespaces]]
binding = "KV"
id = "5eb7a3ae36574f7199e92f46e5537098"
preview_id = "5eb7a3ae36574f7199e92f46e5537098"