name = "bookmark-navigation"
compatibility_date = "2023-10-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
d1_databases = [
  { binding = "DB", database_name = "bookmark-db", database_id = "8a7e0d50-8fb1-4f82-8aec-42f2b8b298ec" }
]

[env.development]
d1_databases = [
  { binding = "DB", database_name = "bookmark-db", database_id = "8a7e0d50-8fb1-4f82-8aec-42f2b8b298ec" }
]
